import Head from 'next/head';

// Components
import Humidity from "../components/Humidity";
import Navbar from "../components/Navbar";
import Temperature from "../components/Temperature";

import { styled } from "styled-components";

const Body = styled.main`
position: relative;
    width: 100%;
    height: 100%;
    margin-bottom: 32px;
`

const Container = styled.div`
max-width: 1440px;
        margin: 0px auto 0 auto;
        position: relative;
        padding: 0px 32px;
`

const Charts = styled.div`
margin-top: 32px;
display: flex;
justify-content: space-between;
align-items: center;
width: 100%;
gap: 32px;
flex-wrap: wrap;
`

const Home = () => {

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Body>
        <Container>
          <Navbar />
          <Charts>
            <Temperature />
            <Humidity />
          </Charts>
        </Container>
      </Body>
    </>
  )
}

export default Home