import Head from 'next/head'

// Components
import Navbar from "../components/Navbar"
import ChartBox from "../components/ChartBox"

import { styled } from "styled-components"

// Data
import { getSheetData } from '../libs/sheets';

const Body = styled.main`
max-width: 1440px;
margin: 0 auto;
padding: 0px 32px;
height: 100%;
width: 100%;
position: relative;
`

const Charts = styled.div`
margin-top: 32px;
display: flex;
justify-content: space-between;
align-items: center;
width: 100%;
gap: 32px;
`

const Home = ({ data }) => {
  console.log(data)

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Body>
        <header>
          <Navbar />
        </header>
        {/* <h1>{data}</h1> */}
        <Charts>
          <ChartBox chartId="temperatur" />
          <ChartBox chartId="humidity" />
        </Charts>
      </Body>
    </>
  )
}

export default Home

export async function getStaticProps(context) {
  const data = await getSheetData();
  return {
    props: {
      sensehat_weather: data.slice(1, data.length), // remove sheet header
    },
    revalidate: 1, // In seconds
  };
}