import Head from 'next/head'
import { useState } from "react"

// Components
import { styled } from 'styled-components'
import Charts from '../components/Charts'
import Documentation from '../components/Documentation'
import Navbar from '../components/Navbar'

// Libs

const Body = styled.main`
    position: relative;
    width: 100%;
    height: 100%;
`

const Container = styled.div`
    max-width: 1440px;
    margin: 0px auto 0 auto;
    position: relative;
    padding: 0px 32px;
`

const Home = () => {
	const [activeContent, setActiveContent] = useState("charts")

	const handleLinkClick = (contentId) => {
		setActiveContent(contentId)
	}

	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta
					name="description"
					content="Generated by create next app"
				/>
				<meta
					name="viewport"
					content="width=device-width, initial-scale=1"
				/>
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<Body>
				<Container>
					<Navbar isActive={activeContent} onClickHandler={handleLinkClick} />
					{activeContent === 'charts' && <Charts />}
					{activeContent === 'code' && <Documentation />}
				</Container>
			</Body >
		</>
	)
}

export default Home
